INFO 2023-11-01 11:46:36,240 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:48:21,467 log Not Found: /api/tasks/1/mark-task/
WARNING 2023-11-01 11:48:46,006 log Not Found: /api/tasks/1/mark-task/
WARNING 2023-11-01 11:51:18,634 log Not Found: /api/tasks/1/mark-task/

INFO 2023-11-01 11:51:49,261 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 11:51:50,284 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:51:51,586 log Not Found: /api/tasks/1/mark-task/

INFO 2023-11-01 11:51:59,380 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 11:52:00,285 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:52:16,172 log Not Found: /api/tasks/1/mark-task/

INFO 2023-11-01 11:52:39,318 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 11:52:40,100 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:52:47,822 log Not Found: /api/tasks/1/mark-task/

INFO 2023-11-01 11:53:05,136 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 11:53:05,914 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:53:33,439 log Not Found: /api/tasks/1/mark-task/

WARNING 2023-11-01 11:53:50,029 log Not Found: /api/tasks/1/marktask/

WARNING 2023-11-01 11:56:46,961 log Not Found: /api/tasks/2/marktask/

INFO 2023-11-01 11:57:58,436 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 11:57:59,201 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 11:58:04,841 log Not Found: /api/tasks/2/marktask/

WARNING 2023-11-01 12:00:51,722 log Not Found: /api/tasks/7/marktask/

WARNING 2023-11-01 12:01:38,948 log Unauthorized: /api/tasks/
WARNING 2023-11-01 12:02:19,263 log Not Found: /api/tasks/marktask/

WARNING 2023-11-01 12:02:56,810 log Unauthorized: /api/login/
INFO 2023-11-01 12:03:51,934 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\TodoApp\settings.py changed, reloading.
INFO 2023-11-01 12:03:52,931 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:03:55,634 log Bad Request: /api/login/
WARNING 2023-11-01 12:07:39,591 log Not Found: /api/signup/
WARNING 2023-11-01 12:09:04,965 log Bad Request: /api/login/
INFO 2023-11-01 12:09:30,086 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\TodoApp\settings.py changed, reloading.
INFO 2023-11-01 12:09:31,243 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:15:57,593 log Unauthorized: /api/login/
INFO 2023-11-01 12:16:13,031 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\TodoApp\settings.py changed, reloading.
INFO 2023-11-01 12:16:13,981 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:16:17,661 log Bad Request: /api/login/
WARNING 2023-11-01 12:24:07,379 log Bad Request: /api/login/
WARNING 2023-11-01 12:24:17,593 log Bad Request: /api/login/
WARNING 2023-11-01 12:24:28,016 log Bad Request: /api/login/
WARNING 2023-11-01 12:32:51,053 log Bad Request: /api/login/
WARNING 2023-11-01 12:32:57,279 log Bad Request: /api/login/
INFO 2023-11-01 12:38:41,556 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 12:38:42,406 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 12:39:05,317 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 12:39:06,090 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 12:39:38,741 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 12:39:39,538 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:40:30,292 log Not Found: /api/tasks/2/marktask/

WARNING 2023-11-01 12:44:01,310 log Unauthorized: /api/tasks/
WARNING 2023-11-01 12:44:29,226 log Forbidden: /api/tasks/
INFO 2023-11-01 12:45:06,415 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 12:45:07,254 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:46:07,963 log Not Found: /api/tasks/12/marktask/

WARNING 2023-11-01 12:47:38,366 log Not Found: /api/tasks/12/marktask/

INFO 2023-11-01 12:48:18,811 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 12:48:19,676 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:49:32,349 log Not Found: /api/tasks/12/marktask/

WARNING 2023-11-01 12:56:47,889 log Not Found: /api/tasks/12/marktask/

INFO 2023-11-01 12:57:05,431 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 12:58:07,399 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 12:58:08,173 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:58:23,338 log Not Found: /api/tasks/12/mark_task/

INFO 2023-11-01 12:58:48,155 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 12:58:48,956 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 12:59:34,470 log Not Found: /api/tasks/12/mark_task/

INFO 2023-11-01 13:06:43,733 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 13:06:44,655 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 13:06:50,181 log Not Found: /api/tasks/12/mark_task/

INFO 2023-11-01 13:06:57,688 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 13:06:58,619 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 13:11:46,822 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 13:11:47,746 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 13:24:41,673 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 13:24:42,713 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 13:24:53,526 log Not Found: /api/tasks/12/mark_task/

INFO 2023-11-01 13:26:47,892 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 13:26:48,691 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 13:27:30,760 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 13:27:31,536 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 13:28:37,946 log Not Found: /api/tasks/12/marktask/

INFO 2023-11-01 13:29:43,436 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 13:29:44,370 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 13:29:49,365 log Not Found: /api/tasks/12/marktask/

WARNING 2023-11-01 13:31:28,128 log Not Found: /api/tasks/2/mark-completed/
WARNING 2023-11-01 13:31:49,026 log Not Found: /api/tasks/12/marktask/

INFO 2023-11-01 13:33:34,886 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 13:33:35,805 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 13:33:40,296 log Not Found: /api/tasks/12/marktask/

WARNING 2023-11-01 14:28:44,698 log Not Found: /api/tasks/12/marktask/

WARNING 2023-11-01 14:33:08,464 log Not Found: /api/tasks/12/marktask/

INFO 2023-11-01 14:36:28,590 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 14:36:29,727 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 14:36:46,962 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 14:36:47,824 autoreload Watching for file changes with StatReloader
WARNING 2023-11-01 14:48:30,062 log Not Found: /api/tasks/12/staus=incomplete

INFO 2023-11-01 14:52:41,255 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 14:52:42,298 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 14:54:00,484 log Internal Server Error: /api/tasks/12/marktask/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 14:54:46,728 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 14:54:47,730 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 14:54:53,741 log Internal Server Error: /api/tasks/12/mark_task_status/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:00:41,635 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:00:42,648 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:14:05,060 log Internal Server Error: /api/tasks/12/mark_task_status/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:16:03,402 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:16:04,264 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:16:14,767 log Internal Server Error: /api/tasks/12/mark_task_status/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:17:29,455 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:17:30,457 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:18:13,175 log Internal Server Error: /api/tasks/12/mark_task_status/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:23:48,362 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:23:49,427 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 15:24:31,574 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:24:32,348 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 15:25:18,770 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 15:25:19,629 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:25:24,841 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
ERROR 2023-11-01 15:25:39,204 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:29:10,801 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:29:11,763 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:29:19,981 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
ERROR 2023-11-01 15:29:39,948 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:29:59,864 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:30:01,176 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 15:31:33,622 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:31:34,419 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:41:31,146 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:42:35,303 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:42:36,207 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 15:44:54,196 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:44:55,038 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:45:06,475 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
ERROR 2023-11-01 15:46:31,988 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:47:06,870 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 15:47:07,704 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:49:41,473 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'marktask'
INFO 2023-11-01 15:51:51,767 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\urls.py changed, reloading.
INFO 2023-11-01 15:51:52,781 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 15:51:56,215 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:14:28,439 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:14:30,212 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 16:15:00,470 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:15:01,433 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:16:31,165 log Internal Server Error: /api/tasks/1/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:16:45,809 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:17:04,525 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:17:26,574 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:17:27,636 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:17:31,278 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:18:17,083 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:19:01,398 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:19:10,981 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:19:17,364 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:20:55,153 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:20:56,406 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:21:01,252 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:21:15,002 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:21:40,773 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:22:05,426 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:22:06,573 autoreload Watching for file changes with StatReloader
INFO 2023-11-01 16:22:22,968 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:22:24,316 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:22:27,867 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:28:47,818 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:28:49,108 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:28:59,034 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:29:07,095 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:29:21,813 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:29:22,854 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:29:28,487 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
ERROR 2023-11-01 16:29:37,184 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:29:51,056 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:29:52,570 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:29:55,853 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
INFO 2023-11-01 16:30:07,026 autoreload C:\Program Files\Jishma\TodoApp (2)\TodoApp\TodoApp\app1\views.py changed, reloading.
INFO 2023-11-01 16:30:08,512 autoreload Watching for file changes with StatReloader
ERROR 2023-11-01 16:38:53,352 log Internal Server Error: /api/tasks/12/mark_task/
Traceback (most recent call last):
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aatoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskViewSet' object has no attribute 'mark_task'
